--[[
--------------------------------------------------------------------------------
- MadeByTheBacon
--------------------------------------------------------------------------------
Thank You for Using Our Flipbook!

We're happy to share our collection of icons, free for you to use. 
While you don't need to credit us, we'd appreciate a mention!

Join my Discord server for more updates and community fun: https://discord.gg/KsYUt8ErxV
or check out my channel:
https://www.youtube.com/channel/UC0AvkeJOmGr-O904S7NOWag

You are welcome to use these icons for your projects. Do not resell them!
Legal Notice:
In accordance with EU Intellectual Property Law, 
legal action will be enforced against unauthorized resale of these icons.

Enjoy the icons, and thank you for supporting our work!
--------------------------------------------------------------------------------
]]

print "MadeByTheBacon was here"